# Generated by Django 6.0.5 on 2026-06-11 07:54

import django.db.models.deletion
import django.utils.timezone
import web.models.character
import web.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='user/photos/default.png', upload_to=web.models.user.photo_upload_path)),
                ('profile', models.TextField(default='Thanks for interesting in my profile!', max_length=500)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=web.models.character.photo_upload_path)),
                ('prompt', models.TextField(max_length=100000)),
                ('background_image', models.ImageField(upload_to=web.models.character.background_image_upload_path)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('greeting', models.TextField(blank=True, max_length=500, null=True)),
                ('profile', models.TextField(max_length=100000)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('voice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('chat_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
        ),
    ]
