# Generated by Django 6.0.5 on 2026-06-06 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
