# Generated by Django 6.0.5 on 2026-06-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_userprofile_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.TextField(default='Thanks for interesting in my profile!', max_length=500),
        ),
    ]
